- name: Install MYSQL server
  hosts: web
  become: true
  tasks: ## Collection or Modules 
  - name: Install MYSQL RPM
    ansible.builtin.package:
      name: httpd
      state: present
      state: enable
    
