- name: Variables from prompt
  hosts: local
  connection: local
  vars_prompt: 
   - name: COURSE
     prompt: please enter course name
     private: false # it is not confidential information
   - name: DURATION
     prompt: please enter course duration
     private: false # it is not confidential information
   - name: TRAINER
     prompt: please enter trainer name
  tasks: 
  - name: print the information
    ansible.builtin.debug: 
      msg: "course is {{ COURSE }}, Duration is {{ DURATION }}, and tainer is {{ TRAINER }}"