- name: Configure nginx server
  hosts: nginx
  become: yes  # become root user 
  tasks:
    - name: Install nginx 
      ansible.builtin.package: 
        name: nginx
        state: present
      
      ansible.builtin.service:
          name: nginx
          state: started

        