- name: Configure nginx server
  hosts: all
  become: yes  # become root user 
  tasks:
   - name: Install nginx 
     ansible.builtin.package: 
      name: nginx
      state: present
   - name: Restarting nginx service
     ansible.builtin.service:
          name: nginx
          state: started

        