- name: Configure nginx server
  hosts: web
  become: yes  # become root user 
  serial: 5
  tasks:
   - name: Install nginx 
     ansible.builtin.package: 
      name: nginx
      state: present
   - name: Restarting nginx service
     ansible.builtin.service:
          name: nginx
          state: started

   - name: print nmgix service
     ansible.builtin.debug:
        msg: "{{ 'Hello world' }}"