- name: create ec2 and route53 record 
  connection: local
  hosts: local
  vars: 
   subnet_id: subnet-07f3507ee3b57dbc7
   sg_id: sg-052223eb3cc8015e5
   ami_id: ami-09c813fb71547fc4f
   instance_type: t2.micro
   instance: 
    - mysql
    - backend
    - frontend
  tasks:
    - name: MYSQL libraries 
      ansible.builtin.pip:
        name: "{{item}}"
        executable: pip3.9
      loop: 
       - boto3
       - botocore

    - name: create ec2 instance 
      amazon.aws.ec2_instance: 
        name: "{{ item }}"
        subnet_id: "{{ subnet_id }}"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
      loop: "{{ instances }}"
      register: ec2_info

    - name: print ec2_info
      ansible.builtin.debug:
        msg: "{{ ec2_info }}"
    
    - name: Print private ip addresses
      ansible.builtin.debug:
        msg: "{{ item.instances[0].private_ip_address }}"
      loop: "{{ ec2_info.results }}"