- name: create ec2 and route53 record 
  connection: local
  hosts: local
  vars: 
   subnet_id: subnet-07f3507ee3b57dbc7
   sg_id: sg-052223eb3cc8015e5
   ami_id: ami-09c813fb71547fc4f
   instance_type: t2.micro
   instance: 
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instance 
    amazon.aws.ec2_instance: 
     name: "{{ item }}"
     subnet_id: "{{ subnet_id }}"
     security_group: "{{ sg_id }}"
     image_id: "{{ ami_id }}"
     instance_type: "{{ instance_type }}"
    loop: "{{ instance }}"
