- name: PING 
  hosts: local
  connection: local
  tasks: ## Collection or Modules 
  - name: Ping the server 
    ansible.builtin.ping:
  -name: Gathering localhost Facts
   ansible.builtin.gather_facts: 